name: provita.com.pl
favicon: null
layout_spectrum: 0.9421418546698987
typography_spectrum: 0.973929924890399
title: PRO VITA Innowacje dla medycyny
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfd'
    - '#28afed'
    - '#1a6084'
    - '#c8c9cb'
  brandStrength: 0.75
  lightness: 0.8215481657534838
  saturation: 0.4375
  rhythmicContrast: 0.7075265881139785
purpose: []
